"""xcut - Hi-C contact matrix enhancement toolkit."""

from xcut.data import (
    BaseContactDataset,
    BaseTransform,
    BinomialDownsample,
    Clip,
    ClipByChromValue,
    ClipByContext,
    ClipByPercentile,
    ClipLogByContext,
    ClipLogByPercentile,
    Compose,
    CoordinateGenerator,
    CoolerDataset,
    DivideByMax,
    EnsureFloat32,
    FixedSizeWrapper,
    HandleNan,
    Identity,
    LogTransform,
    MinMaxNormalize,
    ScaleByChromMax,
    SingleCoolerDataset,
    TensorDataset,
    WindowConfig,
    binomial_downsample,
    create_downsampled_cooler,
    create_transformed_cooler,
    get_log1p_pipeline,
    get_minmax_pipeline,
)

from xcut.inference import create_enhanced_cooler

__version__ = "0.1.0"

__all__ = [
    "create_enhanced_cooler",
    "CoordinateGenerator",
    "WindowConfig",
    "BaseContactDataset",
    "BaseTransform",
    "CoolerDataset",
    "SingleCoolerDataset",
    "TensorDataset",
    "FixedSizeWrapper",
    "Compose",
    "HandleNan",
    "LogTransform",
    "Clip",
    "ClipByChromValue",
    "ClipByPercentile",
    "ClipLogByPercentile",
    "DivideByMax",
    "MinMaxNormalize",
    "ScaleByChromMax",
    "BinomialDownsample",
    "Identity",
    "EnsureFloat32",
    "get_log1p_pipeline",
    "get_minmax_pipeline",
    # Preprocessing
    "binomial_downsample",
    "create_downsampled_cooler",
    "create_transformed_cooler",
    # Backwards compatibility
    "ClipByContext",
    "ClipLogByContext",
]
