name: CCUT Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        mamba-version: "*"
        channels: pytorch, nvidia, conda-forge,bioconda,defaults
        activate-environment: ccut
        environment-file: env.yml
        python-version: 3.11.4
        auto-activate-base: false

    - name: Conda Environment Info
      run: |
        conda info
        conda list

    - name: Run pytest
      shell: bash -l {0}
      run: |
        conda activate ccut
        coverage run -m pytest -v
        coverage html --omit="*/test*" -d ccut/tests/
